// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: games.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const insertGame = `-- name: InsertGame :exec
INSERT INTO game (
    id,
    created_at,
    updated_at,
    date_played
) VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type InsertGameParams struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  sql.NullTime
	DatePlayed time.Time
}

func (q *Queries) InsertGame(ctx context.Context, arg InsertGameParams) error {
	_, err := q.db.ExecContext(ctx, insertGame,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DatePlayed,
	)
	return err
}
