// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: playerDeckGames.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getPlayerGameList = `-- name: GetPlayerGameList :many
SELECT
    player."name" AS player_name,
    deck."name" AS deck_name,
    pdg.is_won,
    game.id AS game_id,
    game.date_played,
    game.game_number,
    game.is_totem
FROM
    player_deck_game pdg
    JOIN player ON pdg.player_id = player.id
    JOIN game ON pdg.game_id = game.id
    JOIN deck ON pdg.deck_id = deck.id
ORDER BY
    date_played DESC
`

type GetPlayerGameListRow struct {
	PlayerName string
	DeckName   string
	IsWon      bool
	GameID     uuid.UUID
	DatePlayed time.Time
	GameNumber int32
	IsTotem    bool
}

func (q *Queries) GetPlayerGameList(ctx context.Context) ([]GetPlayerGameListRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlayerGameList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayerGameListRow
	for rows.Next() {
		var i GetPlayerGameListRow
		if err := rows.Scan(
			&i.PlayerName,
			&i.DeckName,
			&i.IsWon,
			&i.GameID,
			&i.DatePlayed,
			&i.GameNumber,
			&i.IsTotem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
